Fix: Enforce migration bundlers address as receiver for withdraw - issue 27
morpho-org/morpho-blue-bundlers pull request #327
Opened 2023-10-25 12:23 UTC by Jean-Grimal

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/27
Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/25
Fixes #346

2023-10-25 13:11 UTC, Rubilmax reviewed
Ideally this PR is based on #302 and also removes natspecs that were added there

2023-10-25 14:13 UTC, MerlinEgalite approved these changes

2023-10-25 14:16 UTC, Rubilmax approved these changes

2023-10-26 07:29 UTC, Rubilmax requested changes
Natspecs needs to be removed from the `receiver` mention

2023-10-26 09:43 UTC, Rubilmax approved these changes

2023-10-26 10:27 UTC, MerlinEgalite approved these changes

2023-10-30 17:03 UTC, merged