fix(erc4626): adapts slippage
morpho-org/morpho-blue-bundlers pull request #382
Opened 2023-12-11 16:44 UTC by Rubilmax

- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/b0413b48-5b50-4769-835a-b8ed1236b3bd?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed
- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/2bf73196-3629-4ed6-bd8c-3be1f1137bff?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed
- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/27b80ef4-c763-4769-9dde-515451c9f074?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed
- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/5cdb109a-ffd6-496a-a2bb-2c46eb768be1?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed
- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/65f8f161-f2ed-47dc-b6f2-d7fc6dccaf2c?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed

2023-12-11 18:39 UTC, MerlinEgalite commented
Tests are failing :/

2023-12-11 21:31 UTC, adhusson requested changes
I think tests for redeem, deposit and stake are missing.

2023-12-12 10:22 UTC, adhusson approved these changes

2023-12-12 13:26 UTC, MerlinEgalite commented on test/forge/ethereum/EthereumStEthBundlerEthereumTest.sol
> +        bundle.push(abi.encodeCall(StEthBundler.stakeEth, (amount, shares - 2, address(0))));
- 1 does not work?

2023-12-12 13:26 UTC, MerlinEgalite commented on test/forge/ethereum/EthereumStEthBundlerEthereumTest.sol
> +        bundle.push(abi.encodeCall(StEthBundler.stakeEth, (amount, shares - 2, address(0))));
same question as below

2023-12-12 13:55 UTC, Rubilmax commented on test/forge/ethereum/EthereumStEthBundlerEthereumTest.sol
> +        bundle.push(abi.encodeCall(StEthBundler.stakeEth, (amount, shares - 2, address(0))));
Nope, -1 is not enough

2023-12-12 16:02 UTC, MerlinEgalite approved these changes

2023-12-13 08:36 UTC, Jean-Grimal requested changes

2023-12-13 08:36 UTC, Jean-Grimal commented on src/ERC4626Bundler.sol
> +    /// @param shares The amount of shares to mint. Will be capped to the shares corresponding to the bundler's assets.
```suggestion
    /// @param shares The amount of shares to mint. Will be capped at the shares corresponding to the bundler's assets.
```

2023-12-13 08:36 UTC, Jean-Grimal commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Will be capped to the bundler's assets.
```suggestion
    /// @param assets The amount of assets to deposit. Will be capped at the bundler's assets.
```

2023-12-13 08:36 UTC, Jean-Grimal commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to withdraw. Will be capped to the assets corresponding to the owner's
```suggestion
    /// @param assets The amount of assets to withdraw. Will be capped at the assets corresponding to the owner's
```

2023-12-13 08:36 UTC, Jean-Grimal commented on src/ERC4626Bundler.sol
> +    /// @param shares The amount of shares to burn. Will be capped to the bundler's shares.
```suggestion
    /// @param shares The amount of shares to burn. Will be capped at the bundler's shares.
```

2023-12-13 08:36 UTC, Jean-Grimal commented on src/StEthBundler.sol
> +    /// @param amount The amount of ETH to stake. Will be capped to the bundler's balance.
```suggestion
    /// @param amount The amount of ETH to stake. Will be capped at the bundler's balance.
```

2023-12-13 08:39 UTC, Jean-Grimal approved these changes

2023-12-13 09:25 UTC, MerlinEgalite approved these changes

2023-12-20 13:54 UTC, Rubilmax commented
> I think that it's better to pass a share price as slippage parameter (simpler require)

But we need to define a large enough precision for all vault cases...

2023-12-21 09:02 UTC, Jean-Grimal approved these changes

2023-12-21 09:07 UTC, MathisGD commented
blocked by #379

2023-12-21 11:32 UTC, QGarchery commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Will be capped at the bundler's assets.
We use this comment everywhere for the same situation (using a min), I wouldn't change it just here.

2023-12-21 11:32 UTC, QGarchery commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Will be capped at the bundler's assets.
I would also add a warning, something like "beware that you can receive less shares than `minShares` if your balance is less than `assets`"

2023-12-21 11:32 UTC, QGarchery commented on src/ERC4626Bundler.sol
Do we want to do the same thing for the MorphoBundler ?

2023-12-21 13:24 UTC, Rubilmax commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Will be capped at the bundler's assets.
I agree this deserves a dedicated PR, but I do think we should distinguish between the `type(uint256).max` and the "always capped" case

2023-12-21 13:46 UTC, Rubilmax commented on src/ERC4626Bundler.sol
We don't perform `min` in MorphoBundler!

2023-12-21 14:05 UTC, MerlinEgalite approved these changes

2023-12-21 14:41 UTC, Jean-Grimal approved these changes

2023-12-21 15:15 UTC, QGarchery approved these changes

2023-12-21 15:15 UTC, QGarchery commented on src/StEthBundler.sol
> +    /// @param amount The amount of ETH to stake. Will be capped at the bundler's balance.
I think you missed this spot to highlight the min behavior and revert the change on `type(uint256).max`

2023-12-21 16:25 UTC, MerlinEgalite approved these changes

2023-12-21 16:30 UTC, QGarchery commented on src/StEthBundler.sol
> +        require(shares * initialAmount >= minShares * amount, ErrorsLib.SLIPPAGE_EXCEEDED);
Still missing that the minShares is scaled down to handle the min above

2023-12-21 18:16 UTC, Jean-Grimal approved these changes

2023-12-21 18:57 UTC, MathisGD approved these changes
There could be a comment // we verify that shares >= minShares * initialAssets/assets.

2023-12-21 18:58 UTC, merged

2023-12-23 07:08 UTC, StErMi commented
I'll make an example for the `stakeEth` function because the logic is the same for all the other functions involved in the PR

So the user wants to exchange `1000 asset` for `1000 shares` for a `sharePrice` of 1
But in the contracts there are only `500 asset` at this point and the **actual** `sharePrice` is `0,9` (you get more shares)

`shares = 500 / 0,9 = ~555`

`shares * initialAmount >= minShares * amount` ⇒ `555 * 1000 >= 1000 * 500` ⇒ `TRUE`


So **this tx will not revert**, but the user **has minted fewer shares** compared to the `minShares` specified in the function

Is this the intended behavior? Because the number of shares minted is less than `minShares` and it contradicts the natspec/slippage protection input

2023-12-23 07:50 UTC, QGarchery commented
I think your example fits the specification @StErMi, as it is written in the natspec that:
`This parameter is proportionally scaled down in case there are fewer assets than `assets` on the bundler.`
In effect, we are comparing the scaled down assets with the scaled down shares that are actually traded. This means that the slippage mechanism applies to share price, and protects against the negative impact of the share price variation.

Here the share price variation corresponds to positive slippage, so it's expected that this tx is accepted