fix(migration): fix how repay work
morpho-org/morpho-blue-bundlers pull request #383
Opened 2023-12-11 17:23 UTC by Rubilmax

- Fixes https://cantina.xyz/ai/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/1c6fd594-f2f3-4be0-a224-59dfb803f18f
- Fixes https://cantina.xyz/ai/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/c502b812-4879-4b82-8669-7d78255532ca
- Fixes https://cantina.xyz/ai/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/04fdc824-1cc0-434c-b346-298409c87fb9
- Fixes https://cantina.xyz/ai/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/953abb71-c1ed-49e4-9985-7a4938109032
- Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/be9c0906-b10e-48b4-9289-1692c99bfe56

2023-12-11 18:30 UTC, adhusson requested changes
I think https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/953abb71-c1ed-49e4-9985-7a4938109032?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed is not addressed (should take `min(amount,balanceOf(this))` even when `amount = uint.max`).

2023-12-11 18:31 UTC, MerlinEgalite commented on src/migration/AaveV2MigrationBundler.sol
> +    /// @param amount The amount of `asset` to repay. Pass `type(uint256).max` to repay the maximum repayable debt.
do you consider that the bundler balance bounds the "maximum repayable debt"?

2023-12-11 19:00 UTC, Rubilmax commented
> I think [cantina#110](https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/953abb71-c1ed-49e4-9985-7a4938109032?q=status%253Anew%252Cdisputed%252Crejected%252Cduplicate%252Cconfirmed%252Cacknowledged%252Cfixed) is not addressed: in `CompoundV2MigrationBundler` for non-cETH tokens, should take `min(amount,balanceOf(this))` even when `amount = uint.max`.

The thing is CompoundV2 behaves differently than others: it doesn't perform a `min`
Which means if you don't pass `type(uint256).max` to CompoundV2:
- if it is above the debt, it will revert
- if it is below the debt, it will leave dust

But we want to still be able to repay all on CompoundV2

> edit: also some tests would be good

Indeed

2023-12-20 12:57 UTC, MerlinEgalite approved these changes
Approving but it's missing tests IMO

2023-12-20 13:06 UTC, Jean-Grimal approved these changes

2023-12-20 14:24 UTC, MerlinEgalite approved these changes

2023-12-21 10:47 UTC, QGarchery reviewed
I checked the corresponding code base (AaveV2, AaveV3, AaveV3Optimizer and Compond) and this PR correctly address how they handle too high amounts, including `type(uint256).max`

2023-12-21 10:47 UTC, QGarchery commented on src/migration/AaveV2MigrationBundler.sol
> -        if (amount != type(uint256).max) amount = Math.min(amount, ERC20(asset).balanceOf(address(this)));
This change actually removes a feature: revert if not able to completely close the position. If the user wants to have clean (zeroed) positions, this feature would be needed to ensure that. Do you think it's ok to remove it ?

2023-12-21 10:47 UTC, QGarchery commented on src/migration/CompoundV2MigrationBundler.sol
> +    /// Pass `type(uint256).max` to repay the initiator's debt and interest (except for cETH).
Is there a way to compute the debt and interest on Compound ? If yes then we could use it to repay the maximum repayable debt, which is what we want to be able to do (at least for the other migration bundlers)

2023-12-21 11:08 UTC, Rubilmax commented on src/migration/AaveV2MigrationBundler.sol
> -        if (amount != type(uint256).max) amount = Math.min(amount, ERC20(asset).balanceOf(address(this)));
Ah that is the reason I built it this way

2023-12-21 11:28 UTC, MerlinEgalite commented on src/migration/AaveV2MigrationBundler.sol
> -        if (amount != type(uint256).max) amount = Math.min(amount, ERC20(asset).balanceOf(address(this)));
Shouldn't be mostly the goal of the simulation instead? cc @julien-devatom wdyt?

2023-12-21 12:39 UTC, Rubilmax commented on src/migration/AaveV2MigrationBundler.sol
> -        if (amount != type(uint256).max) amount = Math.min(amount, ERC20(asset).balanceOf(address(this)));
https://github.com/morpho-org/morpho-blue-bundlers/pull/316#discussion_r1370255314

2023-12-21 13:18 UTC, Rubilmax reviewed
If this version gets accepted, I need to adapt tests to check that the bundler reverts when trying to repay the whole debt with insufficient funds

2023-12-21 14:13 UTC, MerlinEgalite approved these changes

2023-12-21 14:14 UTC, Jean-Grimal approved these changes

2023-12-21 14:15 UTC, MerlinEgalite requested changes
tests must be updated though i think

2023-12-21 15:28 UTC, Jean-Grimal approved these changes

2023-12-21 16:24 UTC, MerlinEgalite approved these changes

2023-12-21 16:24 UTC, MerlinEgalite commented on test/forge/ethereum/migration/AaveV2MigrationBundlerEthereumTest.sol
> +        callbackBundle.push(_aaveV2Repay(marketParams.loanToken, type(uint256).max - 2));
why don't we want to use `type(uint256).max - 1` instead?

2023-12-21 16:24 UTC, MerlinEgalite commented on src/migration/AaveV2MigrationBundler.sol
> +        // Use `type(uint256).max - 1` because AaveV2 prevents repaying on behalf using `type(uint256).max`.
this is because of these lines

https://github.com/aave/protocol-v2/blob/ce53c4a8c8620125063168620eba0a8a92854eb8/contracts/protocol/libraries/logic/ValidationLogic.sol#L245-L248

2023-12-21 16:24 UTC, MerlinEgalite commented on src/migration/AaveV3MigrationBundler.sol
> +        // Use `type(uint256).max - 1` because AaveV3 prevents repaying on behalf using `type(uint256).max`.
this is because of these lines:

https://github.com/aave/aave-v3-core/blob/6070e82d962d9b12835c88e68210d0e63f08d035/contracts/protocol/libraries/logic/ValidationLogic.sol#L331-L334

2023-12-21 16:57 UTC, QGarchery commented on src/migration/CompoundV2MigrationBundler.sol
> +            amount = Math.min(amount, ICToken(cToken).borrowBalanceCurrent(_initiator));
This can be put in the if above, it would do the same thing since Compound v2 already caps the amount to the borrow balance when it is equal to `type(uint256).max`

2023-12-21 16:57 UTC, QGarchery commented on src/migration/CompoundV2MigrationBundler.sol
> +            require(ICToken(cToken).repayBorrowBehalf(_initiator, amount) == 0, ErrorsLib.REPAY_ERROR);
I understand this fixes old versions of cTokens, but it fails for newer versions no ? It is specified that it returns the actual repay amount now: 
https://github.com/compound-finance/compound-protocol/blob/a3214f67b73310d547e00fc578e8355911c9d376/contracts/CToken.sol#L672

 https://github.com/compound-finance/compound-protocol/blob/a3214f67b73310d547e00fc578e8355911c9d376/contracts/CToken.sol#L672

2023-12-21 17:00 UTC, Rubilmax commented on src/migration/CompoundV2MigrationBundler.sol
> +            require(ICToken(cToken).repayBorrowBehalf(_initiator, amount) == 0, ErrorsLib.REPAY_ERROR);
You point out the return value of the internal function but it is not bubbled up to `repayBorrowBehalf` return value so it's fine

2023-12-21 17:00 UTC, Rubilmax commented on test/forge/ethereum/migration/AaveV2MigrationBundlerEthereumTest.sol
> +        callbackBundle.push(_aaveV2Repay(marketParams.loanToken, type(uint256).max - 2));
Because in this case we want to use (test) the bundler's balance

2023-12-21 17:04 UTC, Rubilmax commented on src/migration/CompoundV2MigrationBundler.sol
> +            amount = Math.min(amount, ICToken(cToken).borrowBalanceCurrent(_initiator));
No, CompoundV2 uses the borrow balance only if input is `type(uint256).max`: https://github.com/compound-finance/compound-protocol/blob/a3214f67b73310d547e00fc578e8355911c9d376/contracts/CToken.sol#L659

2023-12-21 17:04 UTC, Rubilmax commented on src/migration/CompoundV2MigrationBundler.sol
> +            amount = Math.min(amount, ICToken(cToken).borrowBalanceCurrent(_initiator));
This is also true for old cTokens: https://etherscan.io/address/0x39AA39c021dfbaE8faC545936693aC917d5E7563#code#L1894

2023-12-21 17:07 UTC, Jean-Grimal approved these changes

2023-12-21 17:54 UTC, MerlinEgalite approved these changes

2023-12-22 07:44 UTC, QGarchery commented on src/migration/CompoundV2MigrationBundler.sol
> +            require(ICToken(cToken).repayBorrowBehalf(_initiator, amount) == 0, ErrorsLib.REPAY_ERROR);
Ah ok my bad, and now it always returns 0 so this seems to work ok :+1: 

https://github.com/compound-finance/compound-protocol/blob/a3214f67b73310d547e00fc578e8355911c9d376/contracts/CErc20.sol#L102-L105

2023-12-22 07:44 UTC, QGarchery approved these changes

2023-12-22 09:43 UTC, MathisGD commented on src/migration/AaveV3MigrationBundler.sol
> +    /// @param amount The amount of `asset` to repay. Pass `type(uint256).max` to repay the maximum repayable debt.
```suggestion
    /// @param amount The amount of `asset` to repay. Pass `type(uint256).max` to repay the maximum repayable debt (min of the bundler's balance and the debt).
```

2023-12-22 09:44 UTC, QGarchery approved these changes

2023-12-22 09:44 UTC, MathisGD commented on src/migration/AaveV3OptimizerMigrationBundler.sol
> +    /// @param amount The amount of `underlying` to repay. Pass `type(uint256).max` to repay the maximum repayable debt.
```suggestion
    /// @param amount The amount of `underlying` to repay. Pass `type(uint256).max` to repay the maximum repayable debt (min of the bundler's balance and the debt).
```

2023-12-22 09:44 UTC, MathisGD commented on src/migration/CompoundV3MigrationBundler.sol
> +    /// @param amount The amount of `asset` to repay. Pass `type(uint256).max` to repay the maximum repayable debt.
```suggestion
    /// @param amount The amount of `asset` to repay. Pass `type(uint256).max` to repay the maximum repayable debt (min of the bundler's balance and the debt).
```

2023-12-22 09:49 UTC, MerlinEgalite approved these changes

2023-12-22 09:49 UTC, Jean-Grimal commented on test/forge/ethereum/migration/AaveV2MigrationBundlerEthereumTest.sol
> +        callbackBundle.push(_aaveV2Repay(marketParams.loanToken, type(uint256).max - 2));
Should be updated now right ?

2023-12-22 09:50 UTC, Jean-Grimal commented on test/forge/ethereum/migration/AaveV2MigrationBundlerEthereumTest.sol
> +        callbackBundle.push(_aaveV2Repay(marketParams.loanToken, type(uint256).max - 2));
We don't need to pass `type(uint256).max - 2)` anymore right ?

2023-12-22 09:55 UTC, MathisGD commented on src/migration/CompoundV2MigrationBundler.sol
> +    /// @param amount The amount of `cToken` to repay. Pass `type(uint256).max` to repay the maximum repayable debt.
```suggestion
    /// @param amount The amount of `cToken` to repay. Pass `type(uint256).max` to repay the maximum repayable debt (min of the bundler's balance and the debt).
```

2023-12-22 10:25 UTC, merged

2023-12-22 16:37 UTC, StErMi commented on src/migration/CompoundV2MigrationBundler.sol
> +            require(ICToken(cToken).repayBorrowBehalf(_initiator, amount) == 0, ErrorsLib.REPAY_ERROR);
As far as I see `repayBorrowBehalf` always returns `NO_ERROR`. See https://github.com/compound-finance/compound-protocol/blob/master/contracts/CErc20.sol#L104

This was already present in the Cantina audit (and I suggested the removal). See https://github.com/cantinasec/review-morpho-blue-1/issues/24

2023-12-22 16:40 UTC, StErMi commented on src/migration/CompoundV2MigrationBundler.sol
> +        require(ICToken(cToken).redeem(amount) == 0, ErrorsLib.REDEEM_ERROR);
See https://github.com/morpho-org/morpho-blue-bundlers/pull/383/files#r1435207542

Both `CEther` and `CErc20` always return `NO_ERROR` when `redeem` is called. See https://github.com/compound-finance/compound-protocol/blob/master/contracts/CErc20.sol#L54-L63 and https://github.com/compound-finance/compound-protocol/blob/master/contracts/CEther.sol#L49-L58

2023-12-22 16:46 UTC, StErMi commented on src/migration/CompoundV2MigrationBundler.sol
> +            require(ICToken(cToken).repayBorrowBehalf(_initiator, amount) == 0, ErrorsLib.REPAY_ERROR);
I didn't see the remark about `cUSDC` sorry.

2023-12-22 16:47 UTC, StErMi commented on src/migration/CompoundV2MigrationBundler.sol
> +        require(ICToken(cToken).redeem(amount) == 0, ErrorsLib.REDEEM_ERROR);
I didn't see the remark about `cUSDC` sorry.

2023-12-22 17:53 UTC, MerlinEgalite commented on src/migration/CompoundV2MigrationBundler.sol
> +        require(ICToken(cToken).redeem(amount) == 0, ErrorsLib.REDEEM_ERROR);
so all good right?

2023-12-22 18:25 UTC, StErMi commented on src/migration/CompoundV2MigrationBundler.sol
> +        require(ICToken(cToken).redeem(amount) == 0, ErrorsLib.REDEEM_ERROR);
Yes, there's no way to "close" the comment and I didn't want to delete it