feat(bundler): add Sepolia bundler
morpho-org/morpho-blue-bundlers pull request #391
Opened 2023-12-15 08:13 UTC by Rubilmax

The Sepolia bundler does not inherit StEthBundler because Lido doesnt have stETH on Sepolia

2023-12-15 09:44 UTC, Jean-Grimal approved these changes

2023-12-15 11:14 UTC, MerlinEgalite requested changes

2023-12-15 11:14 UTC, MerlinEgalite commented on src/sepolia/SepoliaBundler.sol
> +import {GoerliLib} from "./libraries/GoerliLib.sol";
```suggestion
import {SepoliaLib} from "./libraries/SepoliaLib.sol";
```

2023-12-15 11:14 UTC, MerlinEgalite commented on src/sepolia/SepoliaBundler.sol
> +    constructor(address morpho) WNativeBundler(GoerliLib.WETH) MorphoBundler(morpho) {}
```suggestion
    constructor(address morpho) WNativeBundler(SepoliaLib.WETH) MorphoBundler(morpho) {}
```

2023-12-15 11:14 UTC, MerlinEgalite commented on src/sepolia/libraries/SepoliaLib.sol
> +    address internal constant WETH = 0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9;
this address seems wrong, maybe this address:0x7b79995e5f793a07bc00c21412e50ecae098e7f9

2023-12-15 12:07 UTC, MerlinEgalite approved these changes

2023-12-15 16:16 UTC, MerlinEgalite requested changes

2023-12-15 16:16 UTC, MerlinEgalite commented on src/sepolia/libraries/SepoliaLib.sol
>      /// @dev The address of the WETH contract on Ethereum.
```suggestion
    /// @dev The address of the WETH contract on Sepolia.
```

2023-12-15 16:16 UTC, MerlinEgalite commented on src/sepolia/libraries/SepoliaLib.sol
> +    /// @dev The address of the wstETH contract on Ethereum.
```suggestion
    /// @dev The address of the wstETH contract on Sepolia.
```

2023-12-15 16:27 UTC, MerlinEgalite approved these changes

2023-12-15 17:47 UTC, Jean-Grimal approved these changes

2023-12-16 14:35 UTC, MathisGD commented on src/sepolia/SepoliaBundler.sol
> +    StEthBundler,
?

2023-12-18 07:35 UTC, Rubilmax commented on src/sepolia/SepoliaBundler.sol
> +    StEthBundler,
I deployed a mock since, so the comment of this PR was outdated!

2023-12-18 13:40 UTC, julien-devatom approved these changes

2023-12-18 15:54 UTC, MathisGD approved these changes

2023-12-18 16:09 UTC, merged