Specify `type(uint256).max` behaviors
morpho-org/morpho-blue-bundlers pull request #394
Opened 2023-12-21 14:00 UTC by Rubilmax

2023-12-21 16:33 UTC, MerlinEgalite approved these changes

2023-12-21 16:33 UTC, MerlinEgalite commented
conflicts though @Rubilmax

2023-12-21 20:18 UTC, MathisGD requested changes

2023-12-21 20:18 UTC, MathisGD commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Capped at the bundler's assets.
```suggestion
    /// @param assets The amount of assets to deposit. Capped at the bundler's balance.
```

2023-12-21 20:18 UTC, MathisGD commented on src/TransferBundler.sol
> +    /// @param amount The amount of native tokens to transfer. Capped at the initiator's balance.
```suggestion
    /// @param amount The amount of native tokens to transfer. Capped at the bundler's balance.
```

2023-12-22 07:48 UTC, QGarchery commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Capped at the bundler's assets.
I know we use balance for the ERC20.balanceOf elsewhere, but here I think it's useful to make the distinction between assets and shares (since shares are return by ERC4626.balanceOf)

2023-12-22 07:54 UTC, QGarchery commented on src/migration/AaveV2MigrationBundler.sol
> +    /// interest. Otherwise, the parameter is set to the maximum repayable debt.
```suggestion
    /// interest. Otherwise, the parameter is capped to the maximum repayable debt.
```
because it's also possible to pass a smaller amount

2023-12-22 07:54 UTC, QGarchery commented on src/migration/AaveV3MigrationBundler.sol
> -    /// Pass `type(uint256).max` to repay the initiator's debt and interest.
same

2023-12-22 07:54 UTC, QGarchery commented on src/migration/AaveV3OptimizerMigrationBundler.sol
> -    /// debt. Pass `type(uint256).max` to repay the initiator's debt and interest.
same

2023-12-22 07:54 UTC, QGarchery commented on src/migration/CompoundV3MigrationBundler.sol
> +    /// interest. Otherwise, the parameter is set to the maximum repayable debt.
same

2023-12-22 09:55 UTC, MerlinEgalite approved these changes

2023-12-22 10:00 UTC, MathisGD commented
I'm in favor of merging this in the other PR and review the other one as the changes are closely related

2023-12-22 10:29 UTC, Rubilmax commented
> I'm in favor of merging this in the other PR and review the other one as the changes are closely related

Sorry i read this after having merged the other but in any case this PR also contains independent changes so IMO it is better to have it independent

2023-12-22 10:30 UTC, Jean-Grimal approved these changes

2023-12-22 10:33 UTC, MerlinEgalite approved these changes

2023-12-22 10:57 UTC, MathisGD commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Capped at the bundler's assets.
but it's inconsistent with the other contracts right ?

2023-12-22 11:02 UTC, Rubilmax commented on src/ERC4626Bundler.sol
> +    /// @param assets The amount of assets to deposit. Capped at the bundler's assets.
yes it is inconsistent but still it is clearer in the context of ERC4626

2023-12-22 11:04 UTC, MathisGD approved these changes

2023-12-22 11:07 UTC, QGarchery approved these changes

2023-12-22 11:13 UTC, merged