Add checks in ERC20WrapperBundler
morpho-org/morpho-blue-bundlers pull request #398
Opened 2023-12-27 14:07 UTC by Jean-Grimal

Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/3c786edb-0c0d-4398-a1d3-a1067a935156

2023-12-27 15:33 UTC, MerlinEgalite commented on src/ERC20WrapperBundler.sol
> +        require(success, ErrorsLib.UNSECCESSFULL_DEPOSIT);
```suggestion
        require(success, ErrorsLib.DEPOSIT_FAILED);
```

It's more concise, but better to wait the feedback of others maybe

2023-12-27 16:29 UTC, adhusson commented on src/ERC20WrapperBundler.sol
> +        require(success, ErrorsLib.UNSECCESSFULL_DEPOSIT);
Btw if you keep the original formulation, it's `UNSUCCESSFULL_*` (s/ECC/UCC)

2023-12-27 19:41 UTC, Rubilmax commented on src/ERC20WrapperBundler.sol
> +        require(success, ErrorsLib.UNSECCESSFULL_DEPOSIT);
`UNSUCCESSFUL_*` 😁

2023-12-27 19:43 UTC, Rubilmax reviewed
Code looks good! Is it a real issue though? We could argue the implementation of `ERC20WrapperBundler` is not compatible with non-reverting `ERC20Wrapper` implementations and it could be fine. do we know of wrappers that don't revert and instead return `false`?

The cost of such a late change gets worse and worse as time goes... We are a couple of weeks away from deployment

2023-12-27 19:46 UTC, MerlinEgalite commented
> Code looks good! Is it a real issue though? We could argue the implementation of ERC20WrapperBundler is not compatible with non-reverting ERC20Wrapper implementations and it could be fine. do we know of wrappers that don't revert and instead return false?

Indeed we could say that

> We are a couple of weeks away from deployment

*days btw

2023-12-27 22:59 UTC, MathisGD commented on src/ERC20WrapperBundler.sol
> +        require(success, ErrorsLib.UNSECCESSFULL_DEPOSIT);
```suggestion
        require(ERC20Wrapper(wrapper).depositFor(initiator(), amount), ErrorsLib.UNSECCESSFULL_DEPOSIT);
```

2023-12-27 22:59 UTC, MathisGD commented on src/ERC20WrapperBundler.sol
> +        require(success, ErrorsLib.UNSECCESSFULL_WITHDRAW);
```suggestion
        require(ERC20Wrapper(wrapper).withdrawTo(account, amount), ErrorsLib.UNSECCESSFULL_WITHDRAW);
```

2023-12-28 10:18 UTC, Rubilmax commented on src/libraries/ErrorsLib.sol
> +    string internal constant DEPOSIT_FAILED = "Deposit was unsuccessfull";
```suggestion
    string internal constant DEPOSIT_FAILED = "deposit failed";
```

2023-12-28 10:23 UTC, adhusson approved these changes

2023-12-28 14:24 UTC, MerlinEgalite requested changes

2023-12-28 14:24 UTC, MerlinEgalite commented on src/ERC20WrapperBundler.sol
> +    /// @dev Assumes that `wrapper` implements the `ERC20Wrapper` interface and that the `withdrawTo`function returns a
```suggestion
    /// @dev Assumes that `wrapper` implements the `ERC20Wrapper` interface and that the `withdrawTo` function returns a
```

2023-12-28 14:24 UTC, MerlinEgalite commented on src/ERC20WrapperBundler.sol
> +    /// @dev Assumes that `wrapper` implements the `ERC20Wrapper` interface and that the `depositFor`function returns a
```suggestion
    /// @dev Assumes that `wrapper` implements the `ERC20Wrapper` interface and that the `depositFor` function returns a
```

2023-12-28 15:02 UTC, MerlinEgalite approved these changes

2023-12-28 16:42 UTC, MathisGD approved these changes

2023-12-28 16:42 UTC, MathisGD commented on src/libraries/ErrorsLib.sol
> +    string internal constant WITHDRAW_FAILED = "withdraw failed";
optional 
```suggestion
    /// @dev Thrown when a call to depositFor fails.
    string internal constant DEPOSIT_FOR_FAILED = "deposit for failed";

    /// @dev Thrown when a call to withdrawTo fails.
    string internal constant WITHDRAW_TO_FAILED = "withdraw to failed";
```

2023-12-28 16:53 UTC, Rubilmax commented on src/libraries/ErrorsLib.sol
> +    string internal constant WITHDRAW_FAILED = "withdraw failed";
`depositFor` then? But I think "deposit" alone is fine, shorter and cheaper

2023-12-28 16:56 UTC, merged