build: update optimizer
morpho-org/morpho-blue-bundlers pull request #400
Opened 2024-01-03 08:50 UTC by MerlinEgalite

2024-01-03 09:24 UTC, QGarchery approved these changes

2024-01-03 09:24 UTC, QGarchery commented on foundry.toml
> +optimizer_runs = 999999 # Etherscan does not support verifying contracts with more optimization runs.
```suggestion
optimizer_runs = 999999 # Etherscan does not support verifying contracts with more optimizer runs.
```
let's say that now, so less likely we do a mistake in the future

2024-01-03 13:46 UTC, QGarchery requested changes

2024-01-03 13:46 UTC, QGarchery commented on foundry.toml
> +optimizer_runs = 999999 # Etherscan does not support verifying contracts with more optimizer runs.
Number to change, so probably the description too

2024-01-03 13:46 UTC, QGarchery commented on foundry.toml
Same remark as [this comment](https://github.com/morpho-org/metamorpho/pull/378#discussion_r1440224667) about the outdated link at the end

2024-01-03 14:16 UTC, Jean-Grimal approved these changes

2024-01-03 14:22 UTC, QGarchery approved these changes

2024-01-03 14:26 UTC, merged

2024-01-03 14:28 UTC, MathisGD reviewed
LGTM

2024-01-08 07:12 UTC, Rubilmax commented
What was the rationale behind decreasing the optimization runs?

2024-01-08 07:37 UTC, MerlinEgalite commented
*increase

`optimization_runs` does not work, we must use `optimizer_runs` instead

2024-01-08 07:40 UTC, Rubilmax commented
We did decrease from 999,999 to 80,000 ^^ otherwise understood!

2024-01-08 07:42 UTC, MerlinEgalite commented
> We did decrease from 999,999 to 80,000 ^^ otherwise understood!

Yes but it was not working so in practice we were compiling with 200 😬