Base Bundler
morpho-org/morpho-blue-bundlers pull request #430
Opened 2024-05-06 14:34 UTC by MathisGD

Test and config archi could be refactored (and simplified imo, see #428).
Now I'm missing a [skip cheatcode](https://github.com/foundry-rs/foundry/issues/3845) at the `setUp` stage to be able to skip tests that are not needed on base.

2024-05-06 15:41 UTC, MerlinEgalite commented on .github/workflows/foundry.yml
can you rename this file ethereum as a consequence?

2024-05-06 15:41 UTC, MerlinEgalite commented on config/Configured.sol
> +            revert("chain id must be specified (`--chain <chainid>`)");
perhaps better to select the network by inputing "ethereum" or "base"?

2024-05-07 00:17 UTC, MathisGD commented on config/Configured.sol
> +            revert("chain id must be specified (`--chain <chainid>`)");
but how can you pass this to the tests ?

2024-05-07 08:30 UTC, Rubilmax commented on test/forge/ethereum/EthereumBundlerEthereumTest.sol
These files were supposed to be copy-pasted and adapted to each deployed chain, because the tests may not be identical for all chains; hence the naming that includes the bundler's specific instance for the chain and the chain's name

If you think it is more appropriate to share the same test files for all chains, then this naming is inappropriate anymore and should get rid of the chain's specific name (because it shared for multiple chains)

2024-05-07 08:30 UTC, Rubilmax commented on test/forge/ethereum/EthereumBundlerEthereumTest.sol
Also, the folder `ethereum` should be removed, because test files are shared for multiple chains

2024-05-07 08:30 UTC, Rubilmax commented on src/base/BaseBundlerV2.sol
Suggestion: `BaseMainnetBundlerV2` and rename `Ethereum` to `Mainnet`

2024-05-07 08:32 UTC, Rubilmax commented on test/forge/ethereum/EthereumStEthBundlerEthereumTest.sol
> +    function testStakeEth(uint256 amount) public onlyEthereum {
The fact that most of the tests are skipped for the base network seems to indicate we would be better off duplicating test files into chain-specific folders, and have a configuration file for each chain (as it was planned): `ConfiguredMainnet`, `ConfiguredBaseMainnet`...

2024-05-07 08:38 UTC, adhusson commented on src/base/BaseBundlerV2.sol
> +    Permit2Bundler,
Does the main DAI wrapper on Base (if there is one) manage with normal permit calls?

2024-05-07 08:38 UTC, adhusson commented on config/base.json
> +    "WETH": "0x4200000000000000000000000000000000000006",
What is the difference between getting WETH from `base.json` and getting it from `BaseLib`?

2024-05-07 08:38 UTC, adhusson commented on test/forge/ethereum/EthereumBundlerEthereumTest.sol
> +        }
Given this change `EthereumBundlerEthereumTest` should be renamed.

2024-05-07 08:39 UTC, MathisGD commented on test/forge/ethereum/EthereumBundlerEthereumTest.sol
I think that it makes more sense to have common test yes, because for a same bundler module, we want to test the same thing on all chains.

And indeed, this architecture doesn't make so much sense anymore (see my comment in the desc), I will refactor later but for the moment went for the fastest thing.

2024-05-07 08:48 UTC, MathisGD commented on src/base/BaseBundlerV2.sol
I'm really not a fan of the "mainnet" naming convention. I think that we can keep the weird naming for the moment, and rename "BaseBundler" when working on the bundler V3.

2024-05-07 08:49 UTC, MathisGD commented on test/forge/ethereum/EthereumStEthBundlerEthereumTest.sol
> +    function testStakeEth(uint256 amount) public onlyEthereum {
What is the problem with the fact that a lot of tests are skipped. The bundler doesn't feature these "modules" so it is normal that they are not tested right. Why taking the risk of copying the tests?

2024-05-07 10:29 UTC, MerlinEgalite commented on src/base/BaseBundlerV2.sol
> +    Permit2Bundler,
there's no permit possibility on DAI as it's a canonical `OptimismMintableERC20` contract.

See here: https://basescan.org/token/0x50c5725949a6f0c72e6c4a641f24049a917db0cb#writeContract

2024-05-07 11:10 UTC, MathisGD commented on config/base.json
> +    "WETH": "0x4200000000000000000000000000000000000006",
It's possible too, but it's more streamlined like that (same as all tokens)

2024-05-07 11:47 UTC, adhusson submitted a review, later dismissed

2024-05-07 11:56 UTC, Rubilmax commented on test/forge/ethereum/EthereumBundlerEthereumTest.sol
> we want to test the same thing on all chains

But we could copy-paste all test files and we would be testing the same thing on all chains ^^

Considering some tokens and/or protocols are only available on specific chains, there are test cases that are impossible to share among chains so it seems more complex to share the same test files for all chains and apply exceptions to not run incompatible test cases

2024-05-07 12:03 UTC, Rubilmax commented on test/forge/ethereum/EthereumStEthBundlerEthereumTest.sol
> +    function testStakeEth(uint256 amount) public onlyEthereum {
> What is the problem with the fact that a lot of tests are skipped

The only problem I can see so far is: you need to add specific checks to not run specific tests on specific chains. This is quite simple for now, because there are only 2 chains and a lot of tokens/protocols in common
If we had duplicated test files, we'd only have to delete the tests that don't make sense and inside each test file, the network you are running on is known in advance and the tokens/protocols that exist are provided with the type system via `Configured.sol`

> Why taking the risk of copying the tests?

What risk? Not having the exact same tests on all chains?

This is already mitigated because: tests are not going to change on mainnet and if we add any, we could add them to all chains

2024-05-07 12:04 UTC, Rubilmax approved these changes
Not blocking, I'm just challenging because I do think duplicating test files will be easier to maintain on the long run. We may revert to that later

2024-05-07 12:04 UTC, Rubilmax commented on config/base.json
> +    "cUSDCv2": "0x0000000000000000000000000000000000000000"
(this for example would simply not be defined on base in `ConfiguredBase.sol`)

2024-05-07 15:45 UTC, QGarchery commented on test/forge/fork/PermitBundlerForkTest.sol
>      function setUp() public override {
Do we also want to skip the rest of the setup here if `block.chainid != 1` ?

2024-05-07 15:45 UTC, QGarchery commented on .github/workflows/foundry.yml
> +        chain: [1, 8453]
We can rename the lines `test-ethereum:` and `name: Ethereum tests` above

2024-05-07 15:45 UTC, QGarchery commented on test/forge/fork/BundlerForkTest.sol
(not related to this file) Do we also want to have hardhat tests on Base ? Or move completely from hardhat to foundry since there is accurate gas testing now

2024-05-07 15:45 UTC, QGarchery commented on test/forge/fork/migration/AaveV3MigrationBundlerForkTest.sol
> -    function testMigrateBorrowerWithPermit2(uint256 privateKey) public {
Why does this test fail on Base ? I thought Permit2 was on Base too, with the same address

2024-05-07 16:08 UTC, QGarchery commented on test/forge/fork/migration/AaveV3MigrationBundlerForkTest.sol
> -    function testMigrateBorrowerWithPermit2(uint256 privateKey) public {
It seems like it's because `reserve[DAI].aTokenAddress` returns `address(0)`. I think DAI is not loanable on AaveV3 on Base.
See `getReserveData` [here](https://basescan.org/address/0xe9547fc44c271dbddf94d8e20b46836b87da6789#readContract) and enter the DAI address: `0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb`

2024-05-12 16:42 UTC, MerlinEgalite commented on src/base/BaseBundlerV2.sol
> +    constructor(address morpho) WNativeBundler(BaseLib.WETH) MorphoBundler(morpho) {}
After thinking about it and to have the same address on difference networks I'd be in favor of passing the WETH address as argument.

This way we could have the same address on optimism, arbitrum, etc.

2024-05-13 07:21 UTC, Rubilmax reviewed
partial review

2024-05-13 09:20 UTC, adhusson commented on test/forge/ethereum/EthereumBundlerEthereumTest.sol
With copy/paste you can forget to add a new test in every chain. 

You could also have inheritance: `EthereumTest is EthereumAndBaseTest`, no more copy paste.

But modifiers like `ethereumOnly` or `skipOnBase` don't look complex to me. Visually noisy but very simple to manage.

2024-05-13 11:40 UTC, MathisGD commented on test/forge/fork/BundlerForkTest.sol
>since there is accurate gas testing now

I would like to verify this first, and this is not in the scope of this PR

>Do we also want to have hardhat tests on Base ?

I don't think so, as the gas cost of opcodes is exactly the same on base

2024-05-13 12:10 UTC, QGarchery commented on test/forge/fork/BundlerForkTest.sol
I'm opening an issue for gas testing on forge, otherwise this comment can be resolved

2024-05-13 16:50 UTC, MathisGD commented on src/base/BaseBundlerV2.sol
> +import {BaseBundler} from "../BaseBundler.sol";
If we change the name, I would change it completely: RootBundler for example

2024-05-13 21:17 UTC, MathisGD commented on test/forge/fork/PermitBundlerForkTest.sol
>      function setUp() public override {
I removed this in #432

2024-05-13 21:39 UTC, MathisGD commented on src/base/BaseBundlerV2.sol
> +    constructor(address morpho) WNativeBundler(BaseLib.WETH) MorphoBundler(morpho) {}
Pushed in #433

2024-05-14 10:24 UTC, adhusson commented on test/forge/fork/migration/AaveV3MigrationBundlerForkTest.sol
> +            // To avoid get above the cap.
*getting or going

2024-05-14 11:20 UTC, QGarchery commented on test/forge/fork/migration/AaveV3MigrationBundlerForkTest.sol
> +            // To avoid get above the cap.
Which cap are we talking about ? Is it really that low ?

2024-05-14 11:45 UTC, MathisGD commented on src/base/BaseBundlerV2.sol
Discussion moved to #434

2024-05-14 11:45 UTC, MathisGD commented on src/base/BaseBundlerV2.sol
> +import {BaseBundler} from "../BaseBundler.sol";
discussion moved to #434

2024-05-14 11:45 UTC, MathisGD commented on src/base/BaseBundlerV2.sol
> +    constructor(address morpho) WNativeBundler(BaseLib.WETH) MorphoBundler(morpho) {}
discussion moved there

2024-05-14 11:47 UTC, MathisGD commented on test/forge/fork/migration/AaveV3MigrationBundlerForkTest.sol
> +            // To avoid get above the cap.
the aave supply cap
<img width="248" alt="image" src="https://github.com/morpho-org/morpho-blue-bundlers/assets/74971347/57b0d91f-4585-470b-a011-45f04f348bc8">

2024-05-14 11:48 UTC, QGarchery submitted a review, later dismissed

2024-05-14 12:03 UTC, MerlinEgalite submitted a review, later dismissed

2024-05-14 13:46 UTC, adhusson requested changes

2024-05-14 13:46 UTC, adhusson commented on test/forge/BaseBundlerLocalTest.sol
> -contract BaseBundlerLocalTest is LocalTest {
this file should be renamed to CoreBundlerLocalTest

2024-05-14 14:25 UTC, MerlinEgalite submitted a review, later dismissed

2024-05-14 14:50 UTC, Rubilmax approved these changes

2024-05-14 15:35 UTC, Jean-Grimal commented on test/forge/fork/WNativeBundlerForkTest.sol
why removing the approval from the setup ?

2024-05-14 16:05 UTC, QGarchery commented on src/mocks/AgnosticBundler.sol
> +contract AgnosticBundler is
```suggestion
/// @dev Mock contract, agnostic of the chain, used only for tests.
contract AgnosticBundler is
```
[optional]

2024-05-14 16:07 UTC, MathisGD commented on README.md
the default value is 31337 yes.
I agree that the devx is not ideal
we can either
- manage to not break when chainid=31337 (basically skip all fork tests)
- or make it clear that you should specify either 1 or 31337

2024-05-14 16:26 UTC, Jean-Grimal commented on test/forge/fork/WNativeBundlerForkTest.sol
> +        ERC20(WETH).approve(address(bundler), type(uint256).max);
I think there is a mistake here

It should had been moved to the setup.

2024-05-14 16:30 UTC, MathisGD commented on test/forge/fork/WNativeBundlerForkTest.sol
> +        ERC20(WETH).approve(address(bundler), type(uint256).max);
oops indeed

2024-05-14 16:49 UTC, adhusson commented on README.md
what about making it run on all chains by default?

2024-05-14 16:58 UTC, adhusson commented
I don't think it's a blocker but if I run tests with `--chain` other than 1, I get several repetitions of

```
proptest: Aborting shrinking after the PROPTEST_MAX_SHRINK_ITERS environment variable or ProptestConfig.max_shrink_iters iterations (set 64 to a large(r) value to shrink more; current configuration: 64 iterations)
```

2024-05-14 16:58 UTC, adhusson submitted a review, later dismissed
I don't think it's a blocker but if I run tests with `--chain` other than 1, I get several repetitions of

```
proptest: Aborting shrinking after the PROPTEST_MAX_SHRINK_ITERS environment variable or ProptestConfig.max_shrink_iters iterations (set 64 to a large(r) value to shrink more; current configuration: 64 iterations)
```

2024-05-14 17:31 UTC, MerlinEgalite approved these changes

2024-05-14 17:34 UTC, Jean-Grimal submitted a review, later dismissed

2024-05-14 21:10 UTC, MathisGD commented on README.md
You have an idea to do that ?

2024-05-15 07:54 UTC, QGarchery commented on README.md
I'm fine with any of the above solutions. Not requiring to pass the chainid would be nice though

2024-05-15 07:57 UTC, adhusson commented on README.md
That would be an additional reason duplicate the tests or to use inheritance. You could then run all tests on all forks with just `forge test`.

Otherwise ChatGPT tells me:

```
"test:forge": "bash -c 'for file in config/*.json; do chainId=$(jq -r \".chainId\" \"$file\"); forge test --chain \"$chainId\"; done'",
```

2024-05-15 08:04 UTC, MathisGD commented on README.md
now fork tests run by default on Ethereum

2024-05-15 08:10 UTC, QGarchery approved these changes

2024-05-15 08:18 UTC, MerlinEgalite approved these changes

2024-05-15 09:31 UTC, adhusson approved these changes

2024-05-15 09:32 UTC, merged