Readme update
morpho-org/morpho-blue-bundlers pull request #439
Opened 2024-05-15 11:51 UTC by MathisGD

2024-05-15 13:54 UTC, MerlinEgalite approved these changes

2024-05-16 11:18 UTC, adhusson submitted a review, later dismissed

2024-05-17 08:00 UTC, QGarchery commented on README.md
> +- [EthereumBundlerV2](https://github.com/morpho-org/morpho-blue-bundlers/releases/tag/v1.2.0)
Should we link to V1 also ? I did not find any deployment address related to it on the releases

2024-05-18 17:03 UTC, adhusson approved these changes

2024-05-20 08:32 UTC, QGarchery commented on README.md
> +- [EthereumBundlerV2](https://github.com/morpho-org/morpho-blue-bundlers/releases/tag/v1.0.0)
```suggestion
- [EthereumBundler](https://github.com/morpho-org/morpho-blue-bundlers/releases/tag/v1.0.0)
```
or 
```suggestion
- [EthereumBundlerV1](https://github.com/morpho-org/morpho-blue-bundlers/releases/tag/v1.0.0)
```
but I think it's better to put the name of the contract directly which is `EthereumBundler`

2024-05-20 08:32 UTC, QGarchery commented on README.md
> +![bundler-2 drawio](https://github.com/morpho-org/morpho-blue-bundlers/assets/74971347/59549998-45e5-4154-a93e-6d684247105b)
Note that it will have to be adapted after #441 because of the revert of the renaming of Core Bundler

2024-05-21 15:30 UTC, QGarchery submitted a review, later dismissed

2024-05-21 16:00 UTC, adhusson requested changes

2024-05-21 16:00 UTC, adhusson commented on README.md
> +![bundler](https://github.com/morpho-org/morpho-blue-bundlers/assets/74971347/965feec8-cd15-488e-b97f-644caef96bfc)
Inheritance graph <> code discrepancy: 
* `BaseBundlerV2` does not inherit `PermitBundler` 
* `EthereumBundlerV2` does not inherit `PermitBundler`

Also, the arrows coming out of `StEthBundler` and `WNativeBundler` have almost exactly the same color.

2024-05-21 16:43 UTC, MathisGD commented on README.md
> +![bundler](https://github.com/morpho-org/morpho-blue-bundlers/assets/74971347/965feec8-cd15-488e-b97f-644caef96bfc)
`ChainAgnosticBundlerV2` [inherits](https://github.com/morpho-org/morpho-blue-bundlers/blob/7be911d9148f280b093074381000a6d7d566ff7e/src/chain-agnostic/ChainAgnosticBundlerV2.sol#L20), and on my graph EthereumBundlerV2 does not inherit from PermitBundler. Anyway I made the arrows bigger, to make it clearer

2024-05-21 16:57 UTC, adhusson approved these changes

2024-05-22 07:20 UTC, QGarchery approved these changes

2024-05-22 07:20 UTC, QGarchery commented on README.md
Given the missed dependencies (and renaming) in the graph, this makes me think that a solution where they appear in a text form would be more tractable. Something like [this](https://github.com/morpho-org/metamorpho/tree/main/certora#specification-imports-graph) for example. 
This is just a remark though, potentially to do in another PR or even on other repos

2024-05-22 08:13 UTC, MathisGD commented on README.md
I tried it (#424) and it's almost unreadable. Maybe with a bit more creativity (like grouping some contracts) it could have been.

2024-05-22 08:13 UTC, merged